config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to => "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"

  get 'chat/:id', to: 'chats#show', as: 'chat'

  resources :chats, only: [:create, :show]

  get "search_book" => "books#search_book"

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show ,:edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "daily_posts" => "users#daily_posts"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  # has_many :favorite_books, through: :favorites, source: :book

  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :rooms, through: :user_rooms

  has_many :view_counts, dependent: :destroy

  has_many :books, dependent: :destroy

  has_many :group_users
  has_many :groups, through: :group_users

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  has_one_attached :profile_image

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @book_new = Book.new
    @books = @user.books.page(params[:page])
    @today_book =  @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week

  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit

  end

  def update
    @books = Book.all
    if @user.update(user_params)
      redirect_to user_path, notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def daily_posts

    user = User.find(params[:user_id])
    @books = user.books.where(created_at: params[:created_at].to_date.all_day)
    render :daily_posts_form
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_chart.html.erb
<div class = "table_width">
  <table class="table table-bordered">
    <thead>
      <tr>
       <th>６日前</th>
       <th>5日前</th>
       <th>4日前</th>
       <th>3日前</th>
       <th>２日前</th>
       <th>昨日</th>
       <th>今日</th>
      </tr>
    </thead>
    <tbody>
      <tr>
       <th><%= @books.created_6days.count %></th>
       <th><%= @books.created_5days.count %></th>
       <th><%= @books.created_4days.count %></th>
       <th><%= @books.created_3days.count %></th>
       <th><%= @books.created_2days.count %></th>
       <th><%= @yesterday_book.count %></th>
       <th><%= @today_book.count %></th>
      </tr>
    </tbody>
  </table>
</div>

<canvas id="myChart" width="300" height="100"> </canvas>

    <script> 
    var ctx = document.getElementById("myChart").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'line',                      
        data: {
            labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
            datasets: [{
                label: "投稿数",
                data: [<%= @books.created_6days.count %>, <%= @books.created_5days.count %>, <%= @books.created_4days.count %>, <%= @books.created_3days.count %>, <%= @books.created_2days.count %>, <%= @yesterday_book.count %>, <%= @today_book.count%>],
                backgroundColor: 'rgba(255, 80, 120, 1.0)',
                borderColor: 'rgba(255, 80, 120, 1.0)',
                fill: false
            }]
        },
    });
</script>

app/views/users/_counts.html.erb
<div class = "table_width">
  <table class="table table-bordered">
    <thead>
    <tr>
     <th>今日の投稿</th>
     <th>昨日の投稿</th>
     <th>前日比</th>
    </tr>
    </thead>
    <tbody>
      <tr>
       <td><%= today_book.count %></td>
       <td><%= yesterday_book.count %></td>
       <% if yesterday_book.count == 0 %>
         <td>前日の投稿はなし</td>
       <% else %>
          <td><% the_day_before =   today_book.count / yesterday_book.count.to_f  %>
         　<%= (the_day_before * 100).round %>%</td>
       <% end %>
       </tr>
    </tbody>
  </table>

  <table class="table table-bordered">
    <thead>
    <tr>
     <th>今週の投稿</th>
     <th>先週の投稿</th>
     <th>前週比</th>
    </tr>
    </thead>
    <tbody>
      <tr>
       <td><%= this_week_book.count %></td>
       <td><%= last_week_book.count %></td>
       <% if last_week_book.count == 0 %>
         <td>先週の投稿はなし</td>
       <% else %>
          <td><% the_week_before =   this_week_book.count / last_week_book.count.to_f  %>
         　<%= (the_week_before * 100).round %>%</td>
       <% end %>
       </tr>
    </tbody>
  </table>
</div>

app/views/users/_daily_posts_form.html.erb
<div class="my-3">
  <%= form_with url: user_daily_posts_path(user), method: :get, class: "row justify-content-center", local: false do |f| %>
    <div class="col-auto">
      <%= f.date_field :created_at, class: "form-control" %>
    </div>
    <div class="col-auto">
      <%= f.submit "検索" , class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

<div class="daily_posts_table">
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% unless user == current_user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>Follows</th>
    <th>
      <%= link_to user_followings_path(user) do %>
        <%= user.followings.count %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>Followers</th>
    <th>
      <%= link_to user_followers_path(user) do %>
       <%= user.followers.count %>
      <% end %>
    </th>
  </tr>
</table>

<div class='row'>
  <% if user == current_user %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% else %>
    <td></td>
  <% end %>

  <% unless user == current_user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-secondary" %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
    <% end %>
  <% end %>

  <!-- current_userと@userが一致していない場合に`Begin Chat`を表示 -->

  <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
    <%= link_to 'chatを始める', chat_path(user.id), class: "ml-3" %>
  <% end %>
</div>

app/views/users/daily_posts_form.js.erb
$('.daily_posts_table').html(`
  <h2>検索結果</h2>
  <div class="card" >
    <div class="card-header">投稿数</div>
    <div class="card-body">
      <%= j( @books.count ) %>
    </div>
  </div>
`)

app/views/users/edit.html.erb
<main>
  <%= render 'layouts/errors', obj: @user %>
  <div class='container'>
    <div class='row'>
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <%= form_with model:@user, local:true do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control name" %>
          </div>
         <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
          </div>
          <div class="form-group">
            <%= f.label :introduction %>
            <%= f.text_area :introduction, class: "form-control introduction" %>
          </div>
          <div class="form-group">
            <%= f.submit "Update User", class: 'btn btn-secondary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render '/books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <div><%=link_to "グループを作成する",new_group_path %> | <%=link_to "グループ一覧",groups_path %></div>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <h2>投稿数の前日比・前週比</h2>
      <%= render 'counts', today_book: @today_book, yesterday_book: @yesterday_book, the_day_before: @the_day_before, this_week_book: @this_week_book, last_week_book: @last_week_book, the_week_before: @the_week_before %>
      <h2>7日分の投稿数</h2>
      <%= render 'chart', books: @books, yesterday_book: @yesterday_book, today_book: @today_book %>
      
      <%= render 'daily_posts_form', user: @user %>
    </div>
  </div>
</div>