config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to => "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"

  get 'chat/:id', to: 'chats#show', as: 'chat'

  resources :chats, only: [:create, :show]

  get "search_book" => "books#search_book"

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show ,:edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "daily_posts" => "users#daily_posts"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :view_counts, dependent: :destroy

  belongs_to :user
  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }

  scope :created_2days, -> { where(created_at: 2.days.ago.all_day) }
  scope :created_3days, -> { where(created_at: 3.days.ago.all_day) }
  scope :created_4days, -> { where(created_at: 4.days.ago.all_day) }
  scope :created_5days, -> { where(created_at: 5.days.ago.all_day) }
  scope :created_6days, -> { where(created_at: 6.days.ago.all_day) }

  scope :latest, -> {order(created_at: :desc)}
  scope :star_count, -> {order(star: :desc)}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

  def self.search(search_word)
    Book.where(['category LIKE ?', "#{search_word}"])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only:[:edit, :update]
  def show
    @books = Book.all
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    @book_comment = BookComment.new
    @book_detail = Book.find(params[:id])
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book_detail.id)
      current_user.view_counts.create(book_id: @book_detail.id)
    end
  end

  def index
    @book_new = Book.new
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    books = Book.includes(:favorited_users).
      sort {|a,b|
        b.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
        a.favorited_users.includes(:favorites).where(created_at: from...to).size
      }
    @books=Kaminari.paginate_array(books).page(params[:page])
    if params[:latest]
     @books = Book.latest
    elsif params[:star_count]
     @books = Book.star_count
    else
     @books = Book.all
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path
  end

  def search_book
     @book=Book.new
     @books = Book.search(params[:keyword])
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :star, :category)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_field :category, class: 'form-control book_category' %>
  </div>
  <div class="form-group row" id="star">
    <%= f.label :star,'評価 ', class:'col-md-3 col-form-label' %>
    <%= f.hidden_field :star, id: :review_star %>
  </div>
  <div class="form-group">
    <%= f.submit  class: 'btn btn-success' %>
  </div>
  <!-- 評価javascript -->
  <script>
  $('').empty();
  $('#star').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',

    scoreName: 'book[star]',
    half: false,
  });
  </script>

<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td><%= link_to book.category, search_book_path(keyword: book.category) %></td>
        <td class="favorites_buttons_<%= book.id %>">
          <%= render '/favorites/favorite', book: book %>
        </td>
        <td>
          コメント数: <%= book.book_comments.count %>
        </td>
        <td class="view-count">閲覧数: <%= book.view_counts.count %></td>
        <td id="star-rate<%= book.id%>">
          <script>
            $('#star-rate<%= book.id%>').raty({
              size      : 36,
              starOff   : '<%= asset_path('star-off.png') %>',
              starOn    : '<%= asset_path('star-on.png') %>',
              half      : false,
              readOnly: true,
              score: <%= book.star %>,
            });
          </script>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_search_book.html.erb
<div class="row justify-content-center">
  <% if user_signed_in? %>
    <div class="search_form">
      <%= form_with url: search_book_path, local: true, method: :get do |f| %>
        <%= f.text_field :keyword %>
        <%= f.submit "タグ検索", class: "btn btn-primary" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<main>
  <%= render 'layouts/errors', obj: @book %>
  <div class='container'>
    <div class='row'>
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    		<h1>Editing Book</h1>
    		<%= render 'form', book: @book %>

    		<%= link_to 'Show', @book %> |
    		<%= link_to 'Back', books_path, class: "back" %>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <%= render 'layouts/errors', obj: @book_new %>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <h2>User info</h2>
        <%= render 'users/info', user: current_user %>
        <h2 class="mt-3">New book</h2>
        <%= render 'form', book: @book_new %>
      </div>
      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <p>
          <%= link_to '新しい順', books_path(latest: "true") %>
         |<%= link_to '評価の高い順', books_path(star_count: "true") %>
        </p>
        <%= render 'index', books: @books, book: @book %>
      </div>
    </div>
  </div>
</main>

app/views/books/search_book.html.erb
<table class="table table-hover table-inverse">
  <thead>
  <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th>Tag</th>
  </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= image_tag book.user.get_profile_image, size:'50x50' %></td>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td><%= link_to book.category, search_book_path(keyword: book.category) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"50x50" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td><%= @book.category%></td>
          <td class="favorites_buttons_<%= @book.id %>">
            <%= render '/favorites/favorite', book: @book %>
          </td>
          <td class="comment_count">
            <%= render 'book_comments/comment_count', book: @book %>
          </td>
          <td id="star-rate<%= @book.id%>">
          </td>
          <script>
            $('#star-rate<%= @book.id%>').raty({
              size      : 36,
              starOff   : '<%= asset_path('star-off.png') %>',
              starOn    : '<%= asset_path('star-on.png') %>',
              half      : false,
              readOnly: true,
              score: <%= @book.star %>,
            });
          </script>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% else %>
            <td></td>
            <td></td>
          <% end %>
          <td>
            <p class="view-count">閲覧数: <%= @book_detail.view_counts.count %></p>
          </td>
        </tr>
      </table>
      <div class="comments_area"><%= render '/book_comments/comment', book: @book, book_comment: @book_comment %></div>
    </div>
  </div>
</div>